### ISSUE TITLE
Alignment and size - HELP CTA

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-nab-financial-resilience-quiz#10]
Update font size/style for CTA
![screen shot 2017-10-25 at 10 28 31 pm](https://user-images.githubusercontent.com/25311536/31996342-ecb9c0a4-b9d3-11e7-8a1f-e40b24c041e8.png)

Design
![screen shot 2017-10-25 at 10 25 19 pm](https://user-images.githubusercontent.com/25311536/31996345-f096537c-b9d3-11e7-9f2a-0bd1d04c7b18.png)

**Comment by thiagodebastos** [comment]
fixed
