### ISSUE TITLE
Waiting for results?

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-nab-financial-resilience-quiz#3]
Waited for results to appear, they did not (see attached)

![screen shot 2017-10-25 at 10 07 45 pm](https://user-images.githubusercontent.com/25311536/31995670-20a7a2f8-b9d1-11e7-9a0e-90fce4dc8d0d.png)

**Comment by thiagodebastos** [comment]
@antharca Closing issue as no information provided regarding how to replicate issue.
