### ISSUE TITLE
Graph missing - Question 1

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-nab-financial-resilience-quiz#5]
Visual of graph per design is missing
Button styling inconsistent with design

![screen shot 2017-10-25 at 10 07 24 pm](https://user-images.githubusercontent.com/25311536/31995948-3ae956ba-b9d2-11e7-91b1-2eb474193c30.png)

**Comment by thiagodebastos** [comment]
is this the same as issue #17 ?

**Comment by thiagodebastos** [comment]
fixed
