### ISSUE TITLE
Alignment of question/answers

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-nab-financial-resilience-quiz#7]
Alignment appears skewed. Center align (example of alignment attached)
![screen shot 2017-10-25 at 10 04 33 pm](https://user-images.githubusercontent.com/25311536/31996139-fd7ab9da-b9d2-11e7-91a0-55f88c14ad53.png)

**Comment by thiagodebastos** [comment]
Closing as I can't replicate this. On Chrome, Firefox, Safari
