### ISSUE TITLE
Alignment and styling of CTA buttons vs design

### ISSUE THREAD

**Issue by antharca** [thiagodebastos/glabs-nab-financial-resilience-quiz#9]
Align buttons and copy styling per design

Build:
![screen shot 2017-10-25 at 10 01 36 pm](https://user-images.githubusercontent.com/25311536/31996198-472b2a92-b9d3-11e7-9298-7db05f0b5db2.png)

Design
Bold headings
3 across vs 2 across
BG colour
![screen shot 2017-10-25 at 10 25 04 pm](https://user-images.githubusercontent.com/25311536/31996265-8dba438a-b9d3-11e7-9928-362c7d368789.png)

**Comment by thiagodebastos** [comment]
fixed
